# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - dev

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'AUTOMATICALLY_GENERATED'
  # Change for the name of project
  imageRepository: 'PROJECT_IMAGE_NAME'
  # Azure Portal Domain
  containerRegistry: 'istic.azurecr.io'
  # Dockerfile path
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  # Tag for image version control
  tag: '$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Initial environment variables
  siteUrl: http://localhost:3000
  apiUrl: https://local.url.com
  defaultSrc: local.url.com
  imageSrc: blob.url.com

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
